services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -d chitter_test -f db/migrations/01_create_peeps_table.sql -U postgres
  - psql -d chitter_test -f db/migrations/02_add_peep_time_to_peeps.sql -U postgres

script:
  - bundle exec rspec
