services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, peep TEXT);' -U postgres
  - psql -c 'ALTER TABLE peeps ADD COLUMN time TEXT;' -U postgres

script:
  - bundle exec rspec
